services:
  # -----------------------------------
  # AMBIENTE DE PRODUÇÃO (MASTER)
  # -----------------------------------
  - type: web
    name: mylenna-voice-prod
    runtime: docker
    repo: https://github.com/ingrave-solucoes/mylenna-voice
    branch: master
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 10000
      - key: ENV_TYPE
        value: production
      # As chaves de API devem ser configuradas no Dashboard do Render por segurança
      # ou via Group de Variáveis.
      - key: CHATWOOT_BASE_URL
        value: https://app.ingrave.com.br

  # -----------------------------------
  # AMBIENTE DE DESENVOLVIMENTO (DEVELOP)
  # -----------------------------------
  - type: web
    name: mylenna-voice-dev
    runtime: docker
    repo: https://github.com/ingrave-solucoes/mylenna-voice
    branch: develop
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 10000
      - key: ENV_TYPE
        value: develop
      - key: CHATWOOT_BASE_URL
        value: https://app.ingrave.com.br
